<?php
$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManagerr->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categoryy = $categoryFactory->create()
    ->addAttributeToFilter('is_active', '1')
    ->addAttributeToSelect('name');

$category_ar = [];
$rootId = 0;
$first = false;
foreach ($categoryy as $cate) {

    $curId = intval($cate->getId());
    $parentId = intval($cate->getParentID());

    if ($parentId == 1 && !$first) {
        $rootId = $curId;
        $first = true;
    }

    if (isset($parentId) && $rootId > 0 && $parentId == $rootId) {
        $category_ar[$curId] = [
            "id" => $curId,
            "name" => $cate->getName(),
            "url" => $cate->getURL(),
            "parentId" => $parentId,
            "isActive" => 1,
            "subCategories" => []
        ];
    } else if ($parentId != $rootId && $first && $parentId != 1) {
        if (isset($category_ar[$parentId])) {
            $len = count($category_ar[$parentId]["subCategories"]);
            $category_ar[$parentId]["subCategories"][$len] = [
                "id" => $curId,
                "name" => $cate->getName(),
                "url" => $cate->getURL(),
                "parentId" => $parentId,
                "isActive" => 1
            ];
        }
    }
}
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
?>
<div id="box-filter-m">
    <div class="category-current">
        <?=  $category->getName();?>
    </div>
    <div class="count-p">
        1 Item
    </div>
    <div id="filter-p">
        <span>Filter</span>
    </div>
</div>
<div class="block filter categorySidebar" id="layered-filter-block">
    <h4 class="title-sidaber title-">CATEGORIES</h4>
    <div id='cssmenu'>
        <ul>
            <?php
            foreach ($category_ar as $key) {
                $hasSub = (is_array($key["subCategories"]) && count($key["subCategories"]) > 0) ? true : false;
                ?>
                <li class='has-sub'>
                    <!--                    <a href="-->
                    <?php //echo ($hasSub) ? 'javascript:void(0);' : $key["url"] ?><!--" title="-->
                    <? //= $key['name'] ?><!--">-->
                    <a href="<?php echo $key["url"]; ?>" title="<?= $key['name'] ?>" class="<?= $key['name'] ?>">
                    <span>
                        <?php
                        echo $key['name'];
                        ?>
                    </span>
                    </a>

                    <?php if ($hasSub) { ?>
                        <span class="sign"></span>
                        <ul class="sub-active">
                            <?php foreach ($key["subCategories"] as $subCate) { ?>
                                <li>
                                    <a href="<?= $subCate['url'] ?>" title="<?= $subCate['name'] ?>">
                                        <span><?= $subCate['name'] ?></span>
                                    </a>
                                </li>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){ 
        $(document).ready(function($){
             $('#filter-p').click(function(){
                if($('#layered-filter-block').hasClass('active_filter')){
                    $('#layered-filter-block').removeClass('active_filter');
                    $('.page-products .sidebar-main .filter').removeClass('active_filter');
                } else {
                    $('#layered-filter-block').addClass('active_filter');
                    $('.page-products .sidebar-main .filter').addClass('active_filter');
                }
             });
        });
    });
</script>  