<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<?php
$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();

        $storeManager = $objectManagerr->get('Magento\Store\Model\StoreManagerInterface');
        $currentStore = $storeManager->getStore();
        $baseUrl = $currentStore->getBaseUrl();

$categoryFactory = $objectManagerr->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categoryy = $categoryFactory->create()
    ->addAttributeToFilter('is_active', '1')
    ->addAttributeToSelect('name');

$category_ar = [];
$rootId = 0;
$first = false;
foreach ($categoryy as $cate) {

    $curId = intval($cate->getId());
    $parentId = intval($cate->getParentID());

    if ($parentId == 1 && !$first) {
        $rootId = $curId;
        $first = true;
    }

    if (isset($parentId) && $rootId > 0 && $parentId == $rootId) {
        $category_ar[$curId] = [
            "id" => $curId,
            "name" => $cate->getName(),
            "url" => $cate->getURL(),
            "parentId" => $parentId,
            "isActive" => 1,
            "subCategories" => []
        ];
    } else if ($parentId != $rootId && $first && $parentId != 1) {
        if (isset($category_ar[$parentId])) {
            $len = count($category_ar[$parentId]["subCategories"]);
            $category_ar[$parentId]["subCategories"][$len] = [
                "id" => $curId,
                "name" => $cate->getName(),
                "url" => $cate->getURL(),
                "parentId" => $parentId,
                "isActive" => 1
            ];
        }
    }
}
?>

<nav class="navigation" role="navigation">
        <ul>
            <?php
            foreach ($category_ar as $key) {
                $hasSub = (is_array($key["subCategories"]) && count($key["subCategories"]) > 0) ? true : false;
                ?>
                <li class='category-item level0'>
                    <!--                    <a href="-->
                    <?php //echo ($hasSub) ? 'javascript:void(0);' : $key["url"] ?><!--" title="-->
                    <? //= $key['name'] ?><!--">-->
                    <a href="<?php echo $key["url"]; ?>" title="<?= $key['name'] ?>" class="<?= $key['name'] ?> level-top ui-corner-all">
                    <span>
                        <?php
                        echo $key['name'];
                        ?>
                    </span>
                    </a>
                    <?php if ($hasSub) { ?>
                    <div class="box-child-menu">
                        <ul class="sub-active category-child">
                            <?php foreach ($key["subCategories"] as $subCate) { ?>
                                <li class="level1">
                                    <a href="<?= $subCate['url'] ?>" title="<?= $subCate['name'] ?>">
                                        <span class="title_child"><?= $subCate['name'] ?></span>
                                    </a>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <?php } ?>
                </li>
            <?php } ?>
            <div class="block block-search" id="topSearchWrap">
                <!-- <div class="block block-title"><strong>Search</strong></div> -->
                <div id="clickTopSearchIcon"></div>

                <div class="block block-content">
                    <form class="form minisearch" id="search_mini_form" action="<?= $helper->getResultUrl() ?>" method="get">
                        <div class="field search">
                            <!-- <label class="label" for="search" data-role="minisearch-label"><span>Search</span></label>-->
                            <div class="control">
                                <input id="search"
                                       data-mage-init='{"quickSearch":{
                                            "formSelector":"#search_mini_form",
                                            "url":"<?= $block->getUrl('search/ajax/suggest'); ?>",
                                            "destinationSelector":"#search_autocomplete"}
                                       }'
                                       type="text"
                                       name="<?= $helper->getQueryParamName() ?>"
                                       value="<?= $helper->getEscapedQueryText() ?>"
                                       placeholder="<?= __('What are looking for?'); ?>"
                                       class="input-text"
                                       maxlength="<?= $helper->getMaxQueryLength();?>"
                                       role="combobox"
                                       aria-haspopup="false"
                                       aria-autocomplete="both"
                                       autocomplete="off"/>
                                <div id="search_autocomplete" class="search-autocomplete"></div>
                                <?= $block->getChildHtml() ?>
                            </div>
                        </div>
                        <div class="actions">
                            <button type="submit"
                                    title="<?= $block->escapeHtml(__('Search')) ?>"
                                    class="action search">
                                <span><?= __('Search'); ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </ul>
    </nav>

<div class="block block-search" id="topSearchWrap">
    <!-- <div class="block block-title"><strong>Search</strong></div> -->
    <div id="clickTopSearchIcon"></div>

    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <!-- <label class="label" for="search" data-role="minisearch-label"><span>Search</span></label>-->
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?= $helper->getQueryParamName() ?>"
                           value="<?= $helper->getEscapedQueryText() ?>"
                           placeholder="<?= __('What are looking for?'); ?>"
                           class="input-text"
                           maxlength="<?= $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?= __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){ 
        $(document).ready(function($) {
            $('#topSearchWrap #clickTopSearchIcon').click(function(){
                if ($("#topSearchWrap > .block-content").hasClass("active")){

                    $('#topSearchWrap > .block-content').removeClass('active');
                    $('#topSearchWrap > .block-content').css('display', 'none');
                } else{
                    $('#topSearchWrap > .block-content').addClass('active');
                    $('#topSearchWrap > .block-content').css('display', 'block');
                }
                
            });

            // code category menu child 
            // $('.catalog-category-view .navigation .level0 > .level-top').hover(function($){
            //     $('.category-child').addClass('class_name');
            // });
        }); 
    });
</script>